include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_CONTACT igorns1985@gmail.com)
set(CPACK_PACKAGE_VERSION_MAJOR ${COUNT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${COUNT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${COUNT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${COUNT_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION ${ALPHA_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "static C++ library for count numbers of symbols im string")

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

set(CPACK_RPM_PACKAGE_NAME "count-devel")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "count")
set(CPACK_RPM_CHANGELOG_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md)
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_NAME "libcount-dev")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.0")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

include(CPack)